### ISSUE TITLE
metatables

### ISSUE THREAD

**Issue by unhandyandy** [hoelzro/inline-lua#17]
Any chance that metatables will be supported in the future?

**Comment by hoelzro** [comment]
@unhandyandy It depends on if someone steps in and makes it happen; I only serve as a maintainer (ie. making sure this module builds with the latest & greatest perls, and that there are no bugs).  It's not too simple a task, either, since tables are currently copied between the two environments.  If one wanted to support metatables, tables couldn't be copied (or at least there would have to be a mechanism for getting a reference to a Lua table in Perl), which has potential for breakage.
